# Default values for project4515.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 751503455312.dkr.ecr.us-east-1.amazonaws.com/pgdockrepo
  tag: #BUILD_ID#
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  internalport: #SERVICE_PORT#

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      #kubernetes.io/tls-acme: "true"
  paths:
     path: /project4515
  hosts:
     - pgsandbox.altimetrik.com
  tls:
     - secretName: custom-tls-cert
       hosts:
         - pgsandbox.altimetrik.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {env: common}

tolerations: []

affinity: {}